### ISSUE TITLE
iOS is not respecting cache-control after first conditional get

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#102]

**Comment by seanrucker** [comment]
@chrisrecalis please add any further insights and links to proposed solutions

**Comment by seanrucker** [comment]
@chrisrecalis please add any further insights and links to proposed solutions

**Comment by chrisrecalis** [comment]
http://stackoverflow.com/questions/23826780/nsurlcache-ignores-max-age-on-304-not-modified-responses

We are already using NSHTTPURLResponse so it should just be an `objective-c` to `swift` port. The check can be placed in https://github.com/RoverPlatform/rover-ios/blob/master/Pod/Classes/Network/NetworkOperation.swift#L88

**Comment by chrisrecalis** [comment]
Example to be inserted after https://github.com/RoverPlatform/rover-ios/blob/master/Pod/Classes/Network/NetworkOperation.swift#L88. Needs refactoring as this is my first time doing swift

``` swift
let date = response.allHeaderFields["Expires"] as? String;
if ((date) != nil) {
    let cache = NSURLCache.sharedURLCache().cachedResponseForRequest(self.urlRequest)
    if ((cache) != nil) {
        let cachedResponse = cache?.response as! NSHTTPURLResponse;
        let cachedDate = cachedResponse.allHeaderFields["Expires"] as? String;
        if( date != cachedDate ) {
            let updatedCache = NSCachedURLResponse.init(response: response, data: data!);
            NSURLCache.sharedURLCache().storeCachedResponse(updatedCache, forRequest: self.urlRequest);
        }
    }
}
```

**Comment by seanrucker** [comment]
Tested and looks good now that api proxy is live
