### ISSUE TITLE
Consider optimizing mapping operation

### ISSUE THREAD

**Issue by chrisrecalis** [RoverPlatform/rover-ios#103]
Mapping from JSON to internal models is taking a lot of cpu and time to do. This is really noticeable when loading up a relatively large experience (eg. our `kitchen experience`). It gets worse if there are any other processes taking place while the mapping operation is also processing. I've seen a steady load time anywhere between 500ms to 1 second (@stevietat's device seems to be on the upper end around 800ms, what are you running??). The older the phone the slower the process is as well. Even if experiences are coming from cache they still look like they are being loaded over the internet. Here's an example from my device
<img width="1046" alt="screen shot 2016-09-22 at 8 52 30 pm" src="https://cloud.githubusercontent.com/assets/5234070/18770766/3ddfe0e6-8107-11e6-9359-eced25a3d331.png">

I think sub 200ms loading time would be good and sub 100ms would be ideal as it will look like the experience is more native to the app

**Comment by seanrucker** [comment]
Will do a performance analysis on the 2.x JSON mapping to ensure this is no longer an issue.

**Comment by seanrucker** [comment]
Using the built-in Swift decoding capabilities the time to decode the kitchen experience time has been reduced to 0.03s.
