### ISSUE TITLE
Region Caching

### ISSUE THREAD

**Issue by chrisrecalis** [RoverPlatform/rover-ios#115]
For most user's the regions being monitored for while they are moving hardly change unless they are in a dense geofence / beacon region area. Depending on the device the response can be upward of `4KB`. Saving on this would greatly reduce network traffic.

My initial thoughts would be to save a key generated by the server after the sdk has parsed and successfully passed the regions to the os to monitor for. Any subsequent location updates would pass the key it has stored on disk. The server can then determine if the region list needs to be updated or not.

The reason for storing a key on disk is a safety measure against dropped responses. The server could send a region list but due to network reasons and background duration the sdk might not have a chance to save the list in time for the os to start monitoring for them

**Comment by seanrucker** [comment]
Would we also solve this issue with the asynchronous communication flow we have planned?

**Comment by chrisrecalis** [comment]
Yeah, each state object has its own caching so it would be included. However thats a far ways away and I feel like this is an easy thing to do which accounts for a large portion of our current traffic.

**Comment by seanrucker** [comment]
👍

**Comment by seanrucker** [comment]
This will be resolved with the 2.x architecture.
