### ISSUE TITLE
XPC connection invalid

### ISSUE THREAD

**Issue by Steven-Guo** [RoverPlatform/rover-ios#134]
Hi, 

I'm using Xcode 8.2.1, and I kept getting XPC connection invalid error, hope you guys could help me out. Thank you.

Rover is started in AppDelegate didFinishLaunchingWithOptions: 

_Rover.setup(applicationToken: "xxx")
Rover.registerForNotifications()
Rover.startMonitoring()_

And I've included always in use usage in Info.plist. When the app starts, I've allowed both push notification and location service.

However, I couldn't detect beacon and the console keeps complaining, the log is as below:

_2017-01-18 10:09:32.325569 Test[5865:2631415] [DYMTLInitPlatform] platform initialization successful
Rover [4] - [LocationManager.swift.startMonitoring() - Line 76] => Monitoring started.
Rover [4] - [EventOperation.swift.execute() - Line 106] => Submitting event
    - applicationOpen(2017-01-18 18:09:33 +0000)
Rover [4] - [BluetoothStatusOperation.swift.execute() - Line 34] => Checking Bluetooth status
Rover [4] - [LocationManager.swift.locationManager(_:didUpdateLocations:) - Line 114] => Received location update.
    - <+45.49457551,-122.67176367> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/18/17, 12:05:19 AM Pacific Standard Time
Rover [4] - [BluetoothStatusOperation.swift.centralManagerDidUpdateState - Line 48] => Determined Bluetooth status
    - true
2017-01-18 10:09:33.882353 Test[5865:2631408] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-01-18 10:09:33.931928 Test[5865:2631408] [MC] Reading from public effective user settings.
Rover [4] - [EventOperation.swift.execute() - Line 106] => Submitting event
    - didUpdateLocation(<+45.49457551,-122.67176367> +/- 65.00m (speed -1.00 mps / course -1.00) @ 1/18/17, 12:05:19 AM Pacific Standard Time, 2017-01-18 18:09:33 +0000)
Rover [4] - [BluetoothStatusOperation.swift.execute() - Line 34] => Checking Bluetooth status
2017-01-18 10:09:34.644983 Test[5865:2631408] [CoreBluetooth] XPC connection invalid
Rover [4] - [BluetoothStatusOperation.swift.centralManagerDidUpdateState - Line 48] => Determined Bluetooth status
    - true
Rover [4] - [MappingOperation.swift.main() - Line 56] => Mapped resource of type Event.Type
Rover [4] - [MappingOperation.swift.main() - Line 48] => Mapped collection of type CLRegion.Type
    - 4 items
Rover [4] - [EventOperation.swift.execute() - Line 106] => Submitting event
    - deviceUpdate(2017-01-18 18:09:33 +0000)
Rover [4] - [BluetoothStatusOperation.swift.execute() - Line 34] => Checking Bluetooth status
2017-01-18 10:09:34.855799 Test[5865:2631422] [CoreBluetooth] XPC connection invalid
Rover [4] - [BluetoothStatusOperation.swift.centralManagerDidUpdateState - Line 48] => Determined Bluetooth status
    - true
2017-01-18 10:09:35.174223 Test[5865:2631408] [CoreBluetooth] XPC connection invalid_

Any thoughts on this?

**Comment by seanrucker** [comment]
iOS 10 requires a new `info.plist` entry called "Privacy - Bluetooth Peripheral Usage Description". Have you added that to your app's property list?

**Comment by Steven-Guo** [comment]
Yep, but no luck.

**Comment by seanrucker** [comment]
It should still work even with the connection invalid message. I can see in your logs that it is successfully determining your Bluetooth status is on. If you can't detect beacons there may be another issue. I'll take a look at your account and see if I can spot any configuration issues.

**Comment by seanrucker** [comment]
It looks like you have a few beacons setup in the Proximity app. Can you verify the configurations correctly match your physical beacons and that your beacons are within range of the device you are testing on?

**Comment by seanrucker** [comment]
I can see two devices in your account that are active right now: An iPhone 6 Plus and and iPhone 7 Plus. Which device are you testing on?

**Comment by Steven-Guo** [comment]
I'm using the 6 Plus now.

**Comment by Steven-Guo** [comment]
And no push notification showed up when app is in background, but when I'm in foreground, sometimes I could print out the notification in app delegate, which is weird.

**Comment by seanrucker** [comment]
I can see four beacon enter/exit events from that device last night between 11:01 PM and 11:47 PM PST. Were you testing last night?

All four events were from a beacon with the following configuration (intentionally obfuscated):

UUID: 8492E75F-4FD6-469D-B132-********21D8
Major Number: 6384
Minor Number: 23276

**Comment by Steven-Guo** [comment]
That's correct, I've only succeed once. But no luck after that.

**Comment by seanrucker** [comment]
It looks like you were previously successful detecting beacon events so it appears you have everything setup correctly. Here are some things to check:
- You have your Bluetooth turned on.
- The beacon is still broadcasting the correct configuration.
- If you've connected to the beacon with a configuration app (example Estimote's app) that you have properly saved and exited – otherwise the beacon will no longer broadcast.
- The beacon is in range and has remaining battery life

**Comment by Steven-Guo** [comment]
Thank you Sean. I thought what I did is correct, I will try with other beacons. And two questions: 1. Since APNS is set up in AppDelegate, Rover will handle the alert, no more hooks needed somewhere else, correct? 2. Message will only display at view controllers where Rover is registered as observer, correct?

**Comment by seanrucker** [comment]
1. Yes, as long you have uploaded your certificate correctly in the Settings app and you have implemented the proper hooks in your AppDelegate then notifications will appear automatically. Keep in mind that iOS does not deliver notifications for app's when they are in the foreground.
2. When a user swipes a Rover notification it will be displayed automatically by the Rover SDK. You can customize this if you wish but you do not need to add any observers for the standard behaviour. Rover does everything on its own UIScreen object so it will not interfere with any of your existing view controllers.

**Comment by seanrucker** [comment]
If you're testing notifications on an app built from Xcode you may need to set `Rover.isDevelopment = true`.

**Comment by Steven-Guo** [comment]
Got it, thank you for the explanation, Sean.
