### ISSUE TITLE
Universal link doesn't work

### ISSUE THREAD

**Issue by Steven-Guo** [RoverPlatform/rover-ios#143]
Hi Sean,

According to the doc:
"Rover will automatically generate a site association file for you based on credentials entered in the Rover Settings app. Setting up your site association file is _described on our wiki_. You should make sure this is configured properly before continuing."

I've added associate domains, also the delegate functions, but when open the experience url in browser it just won't launch the app. I am wondering if it is the issue with site association file. However, the wiki page is blank, how could I check it?

**Comment by seanrucker** [comment]
Yes there is admittedly a gap in the documentation. You'll need to setup your Bundle Identifier, App ID Prefix and App Store ID in the Rover Settings app:

https://app.rover.io/settings/ios

The platform will use those values to generate your site association file.

To find your App Store ID visit the [iTunes Link Maker](https://linkmaker.itunes.apple.com/en-us), type the name of your app in the Search field, and select the appropriate country and media type. In the results, click on your app and you will see a "Direct Link" on the bottom of the page. Your App Store ID is the nine-digit number in between id and ?mt.

**Comment by seanrucker** [comment]
We recently switched our mobile-web experiences to use the rover.io domain (previously they were hosted at rvr.co). The SDK currently filters out any URLs that don't belong to rvr.co and will need to be updated.

Offending line:
https://github.com/RoverPlatform/rover-ios/blob/master/Rover/Rover.swift#L271

**Comment by seanrucker** [comment]
@Steven-Guo this is fixed in 1.6.2 released this morning. Feel free to re-open if this is still not working for you.
