### ISSUE TITLE
Rename customer to user

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#157]

**Comment by chrisrecalis** [comment]
@seanrucker when was this decided?

**Comment by seanrucker** [comment]
Not 100% decided, still need to discuss with you and @stevietat but my experience over the past year is that developers and marketers find the term "customer" very confusing. Seems that "user" is the industry standard term for the person using the app and when people think "customer" they think of account owner. This could be simply an SDK and UI change, doesn't necessarily need to be changed on the backend.

**Comment by seanrucker** [comment]
I can't count the number of conversations I've had with our _customers_ explaining what we mean by the term "customer" lol.

**Comment by stevietat** [comment]
We can change to user if it's causing issues. 

I myself haven't run into the term confusing the marketing folk I've interacted with. I can't remember why we originally settled on the term customer...I feel like it had something to do with inferring that we know more about a 'person' beyond just their in-app activities, but also real-world activities as well. (Like when a person enters a store you wouldn't call them a user, but a customer)

As we transition to being less location/beacon/physical world focussed, I think the term user makes sense, especially if it helps clear thins up on the development side. From all the marketing things I've been in most just end up using their own internal labels anyways. (fans, collectors, etc) so I don't think they're very tied to the term 'customer.

**Comment by seanrucker** [comment]
I believe we originally decided on "customer" because we were originally focusing exclusively on retail and in the retail world their internal label is "customer".

**Comment by chrisrecalis** [comment]
I'm up for either. Actually the API has it labeled as a `user` right now

**Comment by chrisrecalis** [comment]
All I know is if we switch to `user` internally @seanrucker promised me a beer ;)

**Comment by seanrucker** [comment]
😲

**Comment by seanrucker** [comment]
Implemented in: https://github.com/RoverPlatform/rover-ios/commit/72bad33792f83f1caed43bea4861c127703ff41d
