### ISSUE TITLE
Capturing advertisingIdentifier can cause a crash

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#181]
We've seen reports of a crash on line 204 of Serializables:

https://github.com/RoverPlatform/rover-ios/blob/master/Rover/Serializables.swift#L204

```
let aid = ASIdentifierManager.shared().advertisingIdentifier.uuidString
```

According to Apple's documentation

> If the value is nil, wait and get the value again later. This happens, for example, after the device has been restarted but before the user has unlocked the device.

I didn't think it was possible for a non-optional in Swift to ever be nil. Seems like a rare-occurrence but worth guarding against.

**Comment by JGVB** [comment]
How do we guard against it?

Have tried

`let id: UUID! = ASIdentifierManager.shared().advertisingIdentifier`
`let id = ASIdentifierManager.shared().advertisingIdentifier as UUID?`
`let id = Optional(ASIdentifierManager.shared().advertisingIdentifier)`

All crash

**Comment by seanrucker** [comment]
@JGVB have you seen crashes in your app due to this? Do you work for one of our customers?

**Comment by seanrucker** [comment]
I believe the fix for this is to first check if advertising is enabled before attempting to access the identifier as per Apple's docs:

https://developer.apple.com/documentation/adsupport/asidentifiermanager

This should not crash regardless and is likely a bug on Apple's side. The fact that the API is still using `shared()` instead of `shared` leads me to believe this has not been touch for a while on Apple's part.
