### ISSUE TITLE
URL Encoding in image urls is lost

### ISSUE THREAD

**Issue by bboralRMN** [RoverPlatform/rover-ios#182]
If I dynamically set an image url to "http://www.google.com?email=some%2Bdude%40rover.io", at some point when Rover SDK makes the call to grab the image, the url encoding is lost, and Rover requests "http://www.google.com?email=some+dude@rover.io."

I think url encoding should be retained here.

**Comment by seanrucker** [comment]
URL encoding is handled automatically by the URL class in Foundation. From my testing it appears that iOS does not believe the "+" or "@" characters require encoding. Throw these lines of code into a Playground:

```swift
let email = URLQueryItem(name: "email", value: "some+dude@rover.io")
let einstein = URLQueryItem(name: "einstein", value: "\"Imagination is more important than knowledge\"")
let loremIpsum = URLQueryItem(name: "lorem ipsum", value: "sit dolor amet")

var components = URLComponents(url: URL(string: "http://www.google.com")!, resolvingAgainstBaseURL: false)!
components.queryItems = [loremIpsum, email, einstein]

let url = components.url!
print(url.absoluteString)
```

The output looks like this:

http://www.google.com?lorem%20ipsum=sit%20dolor%20amet&email=some+dude@rover.io&einstein=%22Imagination%20is%20more%20important%20than%20knowledge%22
