### ISSUE TITLE
Handle open experience in the app doesn't work if the app was previously killed

### ISSUE THREAD

**Issue by albertoNovo** [RoverPlatform/rover-ios#184]
Scenario:
1. App was killed
2. Received a push notification and swipe it
3. **application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any])** is called in the app and inside this method we call **_Rover.didReceiveRemoteNotification(notification, fetchCompletionHandler: nil)_**
4. Before Rover process the notification in the method **didReceiveRemoteNotification(_ userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: ((UIBackgroundFetchResult) -> Void)?, fromLaunch: Bool) -> Bool**, the app is becoming active so once Rover trigger the observer **didReceiveMessage**, the app is already active and in the front end there is no way to know when to handle the notification because the app was inactive or active (it's always active)

**Comment by seanrucker** [comment]
Using the UserNotifications framework as outlined in #185 should solve this.
