### ISSUE TITLE
Rover present 2 experiences if the app was killed and one notification is received

### ISSUE THREAD

**Issue by albertoNovo** [RoverPlatform/rover-ios#185]
Scenario:
1. App was killed
2. Phone swipe a notification related with a experience
3. Inside Rover class, the method **didReceiveRemoteNotification(_ userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: ((UIBackgroundFetchResult) -> Void)?, fromLaunch: Bool) -> Bool** is called twice:
   3.1.The first time after the event **applicationDidOpen** passing fromLaunch **true**
   3.2.The second time after **didReceiveRemoteNotification(_ userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: ((UIBackgroundFetchResult) -> Void)?) -> Bool** is called passing fromLaunch **false**

In both cases the **patchMessage** method is called so the experience is presented twice

**Comment by seanrucker** [comment]
@albertoNovo are you importing the UserNotifications framework in your AppDelegate? What is your Deployment Target?

**Comment by albertoNovo** [comment]
9.0

**Comment by seanrucker** [comment]
Are you importing the UserNotifications framework in your AppDelegate?

**Comment by albertoNovo** [comment]
No, we're not adding the UserNotification framework in the app

**Comment by seanrucker** [comment]
On iOS 10 the system calls the `didReceiveRemoteNotification` methods with some irregularity when swiping notifications. The specific dot release of iOS 10.x.x, whether you have Remote Notifications background mode enabled and the state of the application can all change the way those methods are called. For users running iOS 10+ its recommended to use the UserNotifications framework to handle swipes/taps instead. 

I've updated our documentation to explain how you can use the UserNotifications framework for users running iOS 10 while still supporting users running iOS 9. 

I also added some convenience methods to the framework to make customizing the handling of notifications easier. These methods are available in version 1.8.0 of the SDK which was released this morning. 

Take a look at the following section of the documentation and let me know if this works for you:
https://github.com/RoverPlatform/rover-ios#responding-to-notification-swipestaps

**Comment by seanrucker** [comment]
@albertoNovo did this resolve your issue?

**Comment by seanrucker** [comment]
Another Rover customer reported this same issue and found the above solved his problem. Going to close this issue.
