### ISSUE TITLE
Opening a message from the inbox doesn't update "inbox opens" count

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#20]
When the user opens a message from the inbox it is supposed to register a "message opened" event with the source equal to "inbox". Currently the open count is never incremented on the dashboard unless I swipe it from the notification.

_I'm not sure the exact format of the event endpoint – @chrisrecalis can weigh in on this_

@ata-n this is something we should prioritize, fix and launch as a "dot release" (0.2.1) as it has implications on the architecture. E.g. how do we ensure this event is captured if the developer is in total control over what happens when they click on an inbox item.

**Comment by ata-n** [comment]
gotcha!

The challenge here is, developer is free to do anything with the message. Like you said.. "total control".. i.e use its data from the model to present a custom view controller.
The challenge also becomes clear when considering deep links and websites. In the inbox view controller this process is delegated to the developer. How would an SDK capture such events?
This will also be an issue if developer changes default Rover behaviour on notification swipes!

My suggestion is to provide developer with means to track these events. It would be the responsibility of the developer. 

Thoughts @seanrucker ?

**Comment by seanrucker** [comment]
I think its up to the developer in when integrating the inbox. As long as its a very simple API (e.g. `Rover.captureMessageOpen(message);`) then we can just add documentation instructions to the developer that they must do this.

If they do _not_ override/implement the `didReceiveMessage` method then Rover should do this automatically for them.

If they _do_ override/implement the `didReceiveMessage` method the developer would have to do it themselves, the same as the inbox scenario.
