### ISSUE TITLE
App crash if no connection on the device

### ISSUE THREAD

**Issue by albertoNovo** [RoverPlatform/rover-ios#219]
There is a crash in the EventOperation.swift class. One simple way to reproduce it, is opening the app in airplane mode. The crash happens in this part of the code:

**let serializingOperation = SerializingOperation(model: event) { [unowned networkOperation] JSON in
            networkOperation.payload = JSON
        }** 

It you replace the unowned reference for weak it seems to be fixed.

**Comment by seanrucker** [comment]
Thanks for this @albertoNovo. If you've got a proposed fix would you mind creating a PR?
