### ISSUE TITLE
Add badge number to context

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#223]
https://developer.apple.com/documentation/uikit/uiapplication/1622918-applicationiconbadgenumber

This will be required in order for the server to _increment_ badge number when sending push.

**Comment by seanrucker** [comment]
@chrisrecalis from what I can tell, APNS requires you to set the number you want the badge to. There is no built-in way to _increment_ it. Would this approach work ^^? I.e. store the current badge number in the context and when sending out the notification set the APNS badge property to +1 the current value?

**Comment by chrisrecalis** [comment]
The device is going to report its current badge number and store it as state? Then when a push goes out we take this number increment it by 1 and send it out?

**Comment by chrisrecalis** [comment]
What counts as a badge? inbox unread messges, in-app message?

**Comment by seanrucker** [comment]
Yes.

> What counts as a badge?

Not sure what you mean by that.

**Comment by seanrucker** [comment]
This has been added in the iOS SDK as:

`public var appBadgeNumber: Int?`
