### ISSUE TITLE
Paragraph spacing on 2.x is off

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#287]
Andrea has reported paragraphs with additional line spacing rendering in 2.x. @orospakr can you please look into this?

Additional notes in Dropbox.

**Comment by seanrucker** [comment]
@orospakr I don't think this got fixed. Andrea reported another instance of it.

**Comment by seanrucker** [comment]
@orospakr sounds like this is resolved via a backend fix? If that is confirmed and there is a prioritized backend issue, then can we close this one off?

**Comment by orospakr** [comment]
Backend bug https://github.com/RoverPlatform/rover/issues/2590

**Comment by orospakr** [comment]
Closing mobile-side issue!
