### ISSUE TITLE
Attributes Improvements

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#298]
- [x] AttributeValue should not have a null case
- [ ] Scalar should have a date case
- [x] AttributeValue should not support mixed scalars in its collection
- [x] Make them easier to read
- [x] Make writing nested dictionaries easier
- [ ] Conform to NSCoding

**Comment by seanrucker** [comment]
Scalar date case is hard because we don't specifically know the type of any key so we have to chain a bunch of conditional decoding calls in the `AttributeValue`'s `init(from:)` method. The conditional attempt at decoding to a `Double` works for encoded `Date` values so the conditional attempt at decoding to a `Date` is never run. If we change the order of the conditional decoding attempts then we have the same problem with `Double` (any valid `Double` can be interpreted as a `Date` and vice versa).

Conforming to `NSCoding` is not possible because `AttributeValue` is an enum. To work with CoreData we can instead use a custom value transformer as outlined in the CoreData book.

**Comment by orospakr** [comment]
Superseded by #328.
