### ISSUE TITLE
Event Model

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#328]
- [x] Add a new entity to the .xcdatamodeld file named "Event". Add the following list of attributes, making sure the optional checkbox is _unchecked_ for any of the non-optional values:
   - id: Transformable
   - name: String
   - namespace: String?
   - attributes: Transformable
   - deviceSnapshot: Transformable
   - timestamp: Date
   - isFlushed: Bool (set default to `false`)
- [x] Create a corresponding `Event` class that extends `NSManagedObject`.  Look at the `Beacon` and `Geofence` classes for how to structure this. Create the corresponding `@NSManaged` properties with the following corresponding types:
   - id: UUID
   - name: String
   - namespace: String?
   - attributes: Attributes
   - deviceSnapshot: DeviceSnapshot
   - timestamp: Date
   - isFlushed: Bool
- [x] Override the `awakeFromInsert()` method on the `Event`. In the implementation call `super.awakeFromInsert()` and then set default values for id, attributes, device and timestamp.
   - `self.id = UUID()`
   - `self.attributes = Attributes()`
   - `self.device = DeviceSnapshot()`
   - `self.timestamp = Date()`
- [x] Use the technique outlined in the Core Data book to register custom value transformers for the `deviceSnapshot` and `attributes` properties.

**Comment by orospakr** [comment]
fat fingered it

**Comment by orospakr** [comment]
Done, but we've taken a slightly different approach as discussed offline.

Attributes is now a wrapper class around a dictionary that confirms to NSCoding and Codable.  This gives the nicest tradeoff of not losing auto-generation of Codable for DeviceSnapshot, as well as not breaking Core Data's non-swifty assumptions.

Also UUID on Event is to be a String, not a UUID.
