### ISSUE TITLE
Attempt to Map Predicate to NSPredicate (with LHS field type validations to avoid crashes)

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-ios#389]
[Predicates Spec](https://paper.dropbox.com/doc/Predicates--AU8ehAi3rEVkkEmaePY2ztopAg-QjeJg0q46adihvNybcQp8)

**Comment by orospakr** [comment]
If a blocker presents itself, then implement it exhaustively in pure Swift instead.

**Comment by seanrucker** [comment]
Agreed. Let's attempt to utilize NSPredicate if we can. If we can't, we'll have to roll our own.
