### ISSUE TITLE
Create alternative implementation of Campaigns persistence & API client

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-ios#396]
In lieu of persisting entire model as-is in Core Data, and using same objects/types for both local persistence concern and API client concern, instead this time:

* separate structs for DTO-side, ideally using (mostly) synthesized Codable implementation;
* As-needed local storage with separate managed object classes from DTO. And two separate classes: AutomatedCampaign and ScheduledCampaign.  Leave them blank for now.

(We will add storage of useful information to persisted Campaigns in a later ticket.  This design will flatten out trigger concern.  And individual fields in the trigger(s) can likely also be inlined, so we can have a minimum of complexity in Core Data.)

**Comment by seanrucker** [comment]
👍
