### ISSUE TITLE
Refactor ScreenViewLayout.prepare()

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-ios#404]
ScreenViewLayout is too complex and involves too much nesting.  Swiftlint complains.

**Comment by seanrucker** [comment]
I spent a decent amount of time benchmarking this method and optimizing it for performance. I would suggest not refactoring this and using a SwiftLint comment to bypass the error. The complexity is a tradeoff for performance which is important in this particular method.

**Comment by orospakr** [comment]
Right on. Makes sense to me.
