### ISSUE TITLE
For a given tracked event, query for automated campaigns that apply to the event and the device

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-ios#409]
![image.png](https://images.zenhubusercontent.com/5bbe2648d8943f6b303a8098/80356307-5c45-484d-81d2-f707bd893092)

The green item is the scope of this ticket.

There are several concerns that will go into selecting the automated campaigns that apply to the given observed event:

* Current device state, aka Segmentation;
* Filtering on event contents;
* Filtering by current time.

See the `CampaignAutomatedTrigger` type in GraphQL for more details, namely the `segment` and eventTrigger` fields.  Note that while `EventTriggerFilters` are stored as an array, only one of each type is permitted.

A way of evaluating predicates will be needed.  Rather than implementing an entire implementation of Predicate, consider mapping them to NSPredicate: #389.

Note that in any event DeviceSnapshot may likely need a solution for evaluating keyPaths so the dynamically bound predicates can work.

The Automated Campaign Model in Core Data is currently empty; introduce elements of the Campaign DTO (`CampaignNode`) being synced down into the locally stored one as needed.  Note that some of those fields will need to be queried on, so consider denormalizing/flattening as necessary.

**Comment by seanrucker** [comment]
This is excellent.
