### ISSUE TITLE
Event needed to update customer/device

### ISSUE THREAD

**Issue by chrisrecalis** [RoverPlatform/rover-ios#41]
The sdk and server can get out of sync when information about the customer or device is updated but no core event has been triggered. For example say the user is logged in and has set their identifier to `bagel` and has triggered an `enter beacon` event. The server now knows of a new customer `bagel` with all the current properties. Now if `bagel` were to sign out and not trigger any core event, the server still thinks `bagel` is logged into that device. Any segments built around the customer are still going to target them. Since the inbox is based on the device id the logged out customer is now reading the inbox of the previously logged in customer `bagel`

All the more reason for a state api 👍

**Comment by seanrucker** [comment]
@chrisrecalis I'm not sure the severity of this issue. I've put it in the 1.0.0-rc1 milestone for now but would like to discuss tomorrow when @ata-n is back to see if its ok to defer.

**Comment by seanrucker** [comment]
Closed in #132
