### ISSUE TITLE
Transform Debug App into Sample App.

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-ios#433]
* Demonstrate loading an experience directly from IDs;
* Demonstrate wiring up intent filters in your own activities for handling deep and universal links.

Tests:
1. Present an experience with a custom formed deep link (with and without a campaign ID). I.e. `myapp://rover/123` and  `myapp://rover/123?campaignID=foobar`
2. Present an experience with a universal link (with and without a campaign ID). I.e. `https://myapp.rover.io/abc123` and `https://myapp.rover.io/abc123?campaignID=foobar`

For both of the above tests, verify that the events being tracked include the `foobar` campaign ID when it is passed.

**Comment by seanrucker** [comment]
Closed in #435
