### ISSUE TITLE
Implement Poll Tap and Reveal Animation

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-ios#474]
As specified on the Android ticket RoverPlatform/rover-android#391 .

**Comment by samwoodall** [comment]
### Text Poll Animation
- [x] Whole animation is 1000millis
- [x] All animations start at 0millis
- [x] All animation uses ease in ease out interpolation
- [x] Opacity of vote percentage and voting indicator from 0 -> 1 takes 750millis
- [x] Opacity of results fill bar from 0 -> 1 takes 50millis **EDIT:** This should be to the opacity of the fill bar which might not necessarily be 1
- [x] Result color bar fill and result percentage incrementation duration is 1000millis

For the ease in ease out function I’m going to use this equation `y = x^2/(2*(x^2-x)+1)`
The curve of this looks like 
![Screen Shot 2019-06-28 at 10.59.24 AM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/249f7e1b-e5c4-4bdf-9330-61570a1bca86/Screen+Shot+2019-06-28+at+10.59.24+AM.png)

Here's the text polls animation
https://www.dropbox.com/sh/u7yjzret0jkqv6l/AAA5AHcPPKFGvNXF6DAtbTbSa?dl=0

### Image Poll Animation
- [x] Whole animation is 1000millis
- [x] All animations start at 0millis
- [x] All animations use ease in ease out interpolation
- [ ] If name needs to move to make space for voting indicator the duration is 167millis
- [x] Voting Indicator fade in 0 -> 1, duration is 167millis
- [x] White voting bar fades in 0 -> 0.5, duration is 167millis
- [x] Percentage number fades in 0 -> 1, duration is 167millis
- [x] Overlay fades in. 0 -> 0.3, duration is 167millis
- [x] Result color bar fill and result percentage incrementation duration is 1000millis
- [x] Uses the same ease in ease out function as text polls

Here's the image polls animation
https://www.dropbox.com/s/lth9j5mwse3i9ge/Image%20poll%20animation_2.mp4?dl=0
