### ISSUE TITLE
Recycling image poll view that served a 2-option poll back to a 4-option poll may cause 2 options to disappear.

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-ios#496]
Scroll to the bottom of the experience, then back up to the top. Repeat as necessary.

![IMG_0853](https://user-images.githubusercontent.com/16714/63198135-ca415100-c047-11e9-94c1-24d81359b530.png)

Experience ID `5d56c306a55f03001487dd9a`

**Comment by seanrucker** [comment]
Closed in #497.
