### ISSUE TITLE
Nav bar on websites through landing pages is using ios default style

### ISSUE THREAD

**Issue by chrisrecalis** [RoverPlatform/rover-ios#50]
When clicking a button on a landing page that goes to a website the nav bar style is set to the default ios style instead of inheriting from the landing page.

Below is an example showing how the `light style` was used with a green back button. Clicking the `website` button brought up `https://www.rover.io` but the nav bar style was reset.

<img src="https://cloud.githubusercontent.com/assets/5234070/17223023/d2a84ce2-54c8-11e6-84e4-153d7297fdbc.PNG" width="300" height="534" />

<img src="https://cloud.githubusercontent.com/assets/5234070/17223026/d4dd8734-54c8-11e6-82db-fc7bbf609b2c.PNG" width="300" height="534" />

**Comment by seanrucker** [comment]
This is resolved through moving away from SafariViewController
