### ISSUE TITLE
Web view block has a white background

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#525]
Steps to reproduce:

1. Create a new experience.
1. Add a screen and set its background colour to #FFCC00.
1. Add a web view block to the Screen. 
1. On the "http" tab of the web view inspector, select the Embed option but leave the embed code field blank.
1. Save the experience and open it in the iOS Rover Experiences app.
1. Notice the web view block has a white background, covering the screen.

**Comment by orospakr** [comment]
@seanrucker what is the expected behaviour? transparent?

**Comment by seanrucker** [comment]
Yup. It is transparent on web and Android.

**Comment by seanrucker** [comment]
This should take care of it (untested):

```swift
webView.isOpaque = false
webView.backgroundColor = .clear
webView.scrollView.backgroundColor = .clear
```
