### ISSUE TITLE
Compiler warnings on Xcode 14.2

### ISSUE THREAD

**Issue by ppluskota** [RoverPlatform/rover-ios#555]
I can see a few compiler warnings on Xcode 14.2 in Rover 4.0.1. Can you take a look at that? See attached screenshots
<img width="837" alt="beacon" src="https://user-images.githubusercontent.com/22774595/228447276-2a7e2b8a-8ee7-4f17-bdd3-5a830b130611.png">
<img width="832" alt="location" src="https://user-images.githubusercontent.com/22774595/228447295-f3b096ea-65d9-4543-8f91-ec8bb2420827.png">

**Comment by orospakr** [comment]
Hey @ppluskota yeah, we're aware of these deprecations. Thank you for reporting that they are an issue for you.

We'll resolve them in a future release.
