### ISSUE TITLE
Ability to set Navbar items

### ISSUE THREAD

**Issue by ata-n** [RoverPlatform/rover-ios#58]

**Comment by stevietat** [comment]
This is still an issue, back button appearing when only close button should appear.

![image](https://cloud.githubusercontent.com/assets/1144452/17819870/0f9c59ee-6618-11e6-83b7-4cdbc128c763.png)

vs

![img_1713](https://cloud.githubusercontent.com/assets/1144452/17819905/2a98692c-6618-11e6-87ed-b94ac0c11885.PNG)
