### ISSUE TITLE
Text getting cut off

### ISSUE THREAD

**Issue by stevietat** [RoverPlatform/rover-ios#59]
Text is getting truncated...suspect it might be a discrepancy between letter spacing?

![image](https://cloud.githubusercontent.com/assets/1144452/17706986/487e41b4-63ac-11e6-991f-4c4bd6c89d41.png)

vs CMS:

![image](https://cloud.githubusercontent.com/assets/1144452/17707009/627e4474-63ac-11e6-9306-36d519eb795c.png)

Filling, and lasagna don't appear.

**Comment by seanrucker** [comment]
@stevietat can you confirm this is only related to a slight discrepancy between Chrome font sizing and iOS font sizing. I.e. if you add a few extra pixels to the text block width does it fix the issue?

If so, lets punt this from 1.0.0 and we can fix later, potentially there is something we can do on the console side.

**Comment by stevietat** [comment]
Yes resizing the text-block to have some extra room fixed the issue.

**Comment by seanrucker** [comment]
@ata-n I will move this out of the 1.0.0-rc1 milestone as Stephen confirmed it is a case of slight inconsistencies between iOS and Chrome font rendering. We can pick this up at a later date when we have time to fine tune.
