### ISSUE TITLE
Webview blocks don't display

### ISSUE THREAD

**Issue by chrisrecalis** [RoverPlatform/rover-ios#63]

**Comment by stevietat** [comment]
This is fixed.

Webviews have vertical scrollbars however. Is  this desired? I think we might want to not allow scrolling if possible, so it feels more native, since I believe people will embed only small webviews/vs full websites that require scrolling.

**Comment by chrisrecalis** [comment]
@stevietat we have a property called `scrollable` on web-views we just haven't displayed the option on the front-end yet.
