### ISSUE TITLE
Rover Test App: Inbox not refreshing

### ISSUE THREAD

**Issue by stevietat** [RoverPlatform/rover-ios#65]
Pull down to refresh doesn't seem to refresh the inbox. Sign out of one account, and sign into another. Account from previous inbox remains. Currently only way to refresh is an event (proximity, scheduled push, location update)

**Comment by seanrucker** [comment]
This is only related to the app, so moving out of 1.0.0-rc1 milestone.

**Comment by seanrucker** [comment]
Closing as the app is now part of a separate repository.
