### ISSUE TITLE
Background image on Textbox Covers text

### ISSUE THREAD

**Issue by stevietat** [RoverPlatform/rover-ios#76]
CMS

![image](https://cloud.githubusercontent.com/assets/1144452/17833566/05c276ba-66ef-11e6-9cd3-bf661b99c286.png)

vs 

![image](https://cloud.githubusercontent.com/assets/1144452/17833576/2d1ebd2c-66ef-11e6-9a87-4f1a9e6f5039.png)

**Comment by stevietat** [comment]
Sorry, forgot to add this also affects button blocks.

**Comment by seanrucker** [comment]
@ata-n this still seems to be an issue.

**Comment by seanrucker** [comment]
@stevietat verified this is fixed.
