### ISSUE TITLE
Bold and Semi Bold not being rendered in Textboxes

### ISSUE THREAD

**Issue by stevietat** [RoverPlatform/rover-ios#80]
Textboxes at these weights appear as regular

![img_1725](https://cloud.githubusercontent.com/assets/1144452/17871810/27a7044c-688b-11e6-8906-0bfe70e32fea.PNG)

**Comment by seanrucker** [comment]
@ata-n this was missed from the 1.0.0-rc1 milestone. It may be fixed already?

@stevietat can you verify this is fixed?
