### ISSUE TITLE
Colours mismatch from navbar to content

### ISSUE THREAD

**Issue by stevietat** [RoverPlatform/rover-ios#89]
![img_1779](https://cloud.githubusercontent.com/assets/1144452/18281569/3eac75f4-742b-11e6-9126-e8e68c3cfaad.PNG)

Nav bar and background colour of the row are set to the same colour (804895) but navbar appears lighter.

**Comment by chrisrecalis** [comment]
@stevietat I think this is just ios way of styling by having the navbar semi transparent but @ata-n should confirm. We might need a new field to dictate the transparency of the navbar

**Comment by stevietat** [comment]
Ah ok, yeah, probably then this might be a preview issue for dashboard. Let's wait til @seanrucker gets back to discuss this issue.

**Comment by chrisrecalis** [comment]
Just leaving this here as a resource I found on the tint colors
[https://developer.apple.com/library/ios/qa/qa1808/_index.html](https://developer.apple.com/library/ios/qa/qa1808/_index.html)
